### ISSUE TITLE
Package Manager Not Working

### ISSUE THREAD

**Issue by MacgyverJohnson** [camalot/droidexplorer#59]
@camalot 
Is the package manager a placeholder at this level? Does not seem to work..? tried multiple devices from various brands like samsung galaxy s3 and sony xperia ray... both rooted and busyboxed....USB debugging is enabled and both OEM drivers are installed....I can explore root directory and internalsd and install apks...but how to open package manager..? from tools menu its not working... Using Windows 8.1x64 June 2017 Update with droid explorer 0.9.0.4 x64....During installation several errors were logged(links belows) ...I did run repair installation and this one exited without any error....
https://pastebin.com/hsrhvPfB
https://pastebin.com/4CzeANGU

**Comment by MacgyverJohnson** [comment]
Also app names looks like as if suffering from no unicode(non-latin foreign) character support but showing the names properly on properties dialog box?? I am using US english and no apps are using non english titles

![screenshot 617](https://user-images.githubusercontent.com/17729946/28537889-317134b0-70ce-11e7-9bc4-98980e60e18c.png)

**Comment by camalot** [comment]
The package manager does seem to be broken. it used to "work", but it has been a while since it has. 

The unicode issue is known, and was addressed in the MADB library (which will eventually be what is handling the communication between Droid Explorer and the Android Device). 

Part of my issue is finding the time to work on fixing the package manager, and moving forward with pulling in the MADB refactoring stuff.

**Comment by MacgyverJohnson** [comment]
Thanks for the swift response dev...Always ready for beta testing and giving bug reports :)
