### ISSUE TITLE
Droid Explorer tries to connect to ADB as root in Android Oreo

### ISSUE THREAD

**Issue by antoniu200** [camalot/droidexplorer#68]
Hello! So, I have bought myself a Sony Xperia XZ1 Compact and I have unlocked the bootloader, rooted it and now I want to modify the stock Sony Android, which seems to be pretty hard since they secured the OS more than it used to be in Android Nougat AOSP. So, to make my work easier, I tried to run Droid Explorer, but it connects to ADB as root like this: "adb root", instead of like this: "

adb shell
su", method that I tested on this device and seems to work. And also, I think it would work on any rooted device, as any rooted device allows access to "su" command. Please include this into the next update of the app.

**Comment by camalot** [comment]
`adb root` is not the same as `adb shell su`. 

The `adb root` command restarts the adbd daemon with root permissions. 

http://adbshell.com/commands/adb-root

**Comment by antoniu200** [comment]
Thanks for closing the issue, so nobody can see it. Yes, it practically is the same as adb root, because now you can execute commands directly from the Android shell, without needing to restart adb as root. By running adb as root, the device can just deny the request and close the connection, like you did with my thread. But by going into shell, you can do the same things, without giving the device the posibility to ignore the request and deny it without questioning the user, again, like you did with me.

And on Sony's Android 8, that's exactly what happens: the root request is being revoked without questioning the user and the connection with the PC is closed.

If you hate your program's users, why'd you create it then? Or why do you even allow us to submit issues? This is an issue with your program! And adb shell can fix this!

**Comment by camalot** [comment]
everyone can see it. I closed it, not deleted.

adb root starts the daemon on the device with root permissions, as i already stated.  `adb shell su` launches a shell process as `root`. Those are 2 completely different things. The adbd daemon is the communication service that adb on your pc uses to communicate with your phone. If `adb root` does not work, it does not impact how droid explorer works going forward, it only limits how it does some tasks that it runs to do things like copy files. 

your "issue" does not provide any information on what the problem actually is, just a "solution" that is not a real solution, because droid explorer does use `adb shell su` when it needs to execute as root. 

If you are having an actual problem, please open an issue with what the problem is, what you are trying to do, what the result, or errors, that you get, and what you expect.

**Comment by antoniu200** [comment]
Please read what I said my phone does when it recieves adb root command. That's my issue. There is no error. Droid Explorer can't find the device, but that just leaves the option "your phone is not rooted", if you won't read what I wrote, because otherwise it doesn't make sense.

**Comment by camalot** [comment]
I read it, and just re-read it. I do not see any thing about what happens when it receives `adb root`. All it says about adb root is:

> but it connects to ADB as root like this: "adb root", instead of like this: "adb shell su"

But you can turn off the warning you get about not being able to run `adb root`.  There should be an option to "continue", or "continue with more info". 

The more info goes to here: 
https://android.stackexchange.com/questions/95894/droid-explorer-permission-denied-when-accessing-root-only-folders/96066#96066

See if any of that info helps with your problem. 

From the sound of it, it seems that your phone does not support `adb root`, which is normal for stock builds of android.

**Comment by antoniu200** [comment]
So, basically, what you're telling me is that it is ok to have a program that won't work on a lot of devices (because a lot of us se AOSP, Lineage, RR), but when I tell you how you can solve that you won't? I understood that your program uses adb commands, but the commands needed to list files, rename files, move files, basically do any file operation exist under shell too. Are you too lazy to rewrite the program?

Anyway, your link didn't help. And what my hone does when ot recoeves adb root is automatically reject it and cut the connection with computer completely; no more charging, no more data transfers, no nothing. To reconnect to the computer, I need to reboot the phone.

**Comment by camalot** [comment]
So i was willing to work with you and help you solve your problem. but if you are going to talk to me like it is my responsibility to make sure it works for every single device, and then call me lazy too "rewrite it"...  I provide this software as is, and offer the support I can, in my free time. This is not a job, this is not a company. It is a personal project.

Your "solution" will not fix the problem you are describing. As I said, droid explorer already uses that style of commands under the hood. It uses `adb shell su` to run all the other commands, it ONLY uses the adb root at the beginning. And the link I sent you explains all of it, and how to potentially use it on stock roms. 

I wrote this in my free time, starting 9 years ago. The code is there, feel free to implement the fix, and submit a pull request to get it working. I don't have the time, money, or resources to test with every single phone.

**Comment by antoniu200** [comment]
Actualy, no, you were in no way, shape, or form willing to work with me. If you were, you wouldn't have closed my thread immediately.

And it doesn't have to be tesyed on all phones. I wasn't requesting you to test it on all devices, I was requesting you to stio using adb root, because there is no point as you can access adb shell su, which will take any root command and execute it successfully.

But anyway, it's you program, you can do whatever you want with it. I was hoping I could get some help or some willfullness here, but from the first moment you showed lack of interest for this issue, thread and recommendation. And if you're attacking my attitude, first take a look at yours. I'm done.

**Comment by camalot** [comment]
The issue, was closed because it is still an issue that does not have information describing what the actual problem is, as I said in my second reply. 

I know you were asking me to stop using `adb root`, and as I stated a number of times, that command is not the same as running `adb shell su`. `adb shell su` runs a shell as root, `adb root` restarts the `adbd daemon` as root. To have access to folders on the system, that require root, adbd needs to be running as root. Take a look at [adb shell su works, but adb root does not](https://stackoverflow.com/questions/25477424/adb-shell-su-works-but-adb-root-does-not), maybe that will provide you more information as to why they are different, and what it does.

If i wasn't trying to help, I wouldn't have even replied to the issue at all. I could have just let it sit open and unanswered. But I wish you well with modifying your phone.
